Resources:
  YoutubeCutterProdMonitoringLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
                - events.amazonaws.com
                - scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
      - PolicyName: LambdaExecutionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
                - s3:*
              Resource: arn:aws:s3:::*
            - Effect: Allow
              Action:
                - "lambda:InvokeFunction"
              Resource: "arn:aws:lambda:*:*:function:*"
            - Effect: Allow
              Action:
                - "ssm:GetParameter"
                - "SNS:Publish"
                - "dynamodb:*"
              Resource: "*"
  YoutubeCutterProdMonitoringEventbridgeRule:
    Type: AWS::Scheduler::Schedule
    Properties:
      ScheduleExpression: "rate(1 hour)"
      FlexibleTimeWindow:
        Mode: 'OFF'
      ScheduleExpressionTimezone: Etc/UTC
      Target:
        Arn: !GetAtt YoutubeCutterProdMonitoringLambdaFunction.Arn
        RoleArn: !GetAtt YoutubeCutterProdMonitoringLambdaRole.Arn

  # NOTE: If you want to update the layer, you need to change the s3 key because cfn won't detect an updated s3 file.
  YoutubeCutterProdMonitoringLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes: 
        - python3.9
      Content: 
        S3Bucket: "youtube-cutter-private-prod"
        S3Key: "monitoring-lambda/monitoring-dep-layer.zip"
      Description: "Lambda layer containing python dependencies for youtube cutter monitoring."
      LayerName: "YoutubeCutterProdMonitoringLambdaLayer"

  # NOTE: If you want to update the layer, you need to change the s3 key because cfn won't detect an updated s3 file.
  YoutubeCutterProdMonitoringLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Monitors various functionalities of wav.ninja and makes sure they're working properly."
      FunctionName: "YoutubeCutterProdMonitoring"
      Handler: monitoring.handle
      MemorySize: 128
      Role: !GetAtt YoutubeCutterProdMonitoringLambdaRole.Arn
      Runtime: python3.9
      Timeout: 300
      Code:
        S3Bucket: "youtube-cutter-private-prod"
        S3Key: "monitoring-lambda/monitoring.zip"
      Layers:
        - !Ref YoutubeCutterProdMonitoringLambdaLayer