#cloud-config
package_update: true
package_upgrade: true

runcmd:
  # install required packages
  - apt update
  - apt install -y docker.io
  - apt install -y unzip
  - apt install -y python3.12-venv

  - apt install -y ca-certificates curl gnupg

    # keyring
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg

    # repo (auto-detect codename)
  - CODENAME=$(. /etc/os-release && echo "$VERSION_CODENAME")
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $CODENAME stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

  - apt update
  - apt install -y docker-compose-plugin

  - echo "[CUSTOM] Pulling down aws cli"
  - curl -o "awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
  - unzip awscliv2.zip
  - ./aws/install
  - rm -rf awscliv2.zip
  - rm -rf aws

  - echo "[CHECKPOINT]"
  - mkdir -p /audio
  - cd /opt
  - git clone https://github.com/chang432/youtube-cutter.git
  - mv youtube-cutter/docker ./
  - rm -rf youtube-cutter
  - cd docker
  - python3 -m venv venv
  - venv/bin/pip install -r requirements.txt

  - reboot

  - chmod +x /opt/docker/start_cloud.sh
  - (crontab -l 2>/dev/null; echo "*/1 * * * * /opt/docker/start_cloud.sh >> /var/log/start.log 2>&1") | crontab -
  - chmod +x /opt/docker/cleanup.sh
  - (crontab -l; echo "*/10 * * * * /opt/docker/cleanup.sh >> /var/log/cleanup.log 2>&1") | crontab -  
  - chmod +x /opt/docker/hourly.sh
  - (crontab -l; echo "*/30 * * * * /opt/docker/hourly.sh >> /var/log/hourly.log 2>&1") | crontab -  
  - chmod +x /opt/docker/daily.sh
  - (crontab -l; echo "50 23 * * * /opt/docker/daily.sh >> /var/log/daily.log 2>&1") | crontab -     # 11:50 PM daily
  