#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - HOST_ENDPOINT=$(curl https://api.ipify.org)
  - echo "HOST_ENDPOINT=${HOST_ENDPOINT}" > /etc/environment

  # install required packages
  - apt install -y docker.io
  - apt install -y docker-compose
  - apt install -y unzip

  - echo "[CUSTOM] Pulling down aws cli"
  - curl -o "awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
  - unzip awscliv2.zip
  - ./aws/install
  - rm -rf awscliv2.zip
  - rm -rf aws

  - echo "[CHECKPOINT]"
  - mkdir -p /audio
  - cd /opt
  - git clone https://github.com/chang432/youtube-cutter.git
  - mv youtube-cutter/docker ./
  - rm -rf youtube-cutter

  - reboot

  - chmod +x /opt/docker/start_cloud.sh
  - (crontab -l 2>/dev/null; echo "*/1 * * * * /opt/docker/start_cloud.sh >> /var/log/start.log 2>&1") | crontab -
  - chmod +x /opt/docker/cleanup.sh
  - (crontab -l; echo "*/10 * * * * /opt/docker/cleanup.sh >> /var/log/cleanup.log 2>&1") | crontab -  
  - (crontab -l; echo "0 0 * * * echo "" > /var/log/cleanup.log") | crontab -     # Refresh cleanup.log daily
  