#cloud-config
package_update: true
package_upgrade: true

runcmd:
  # install required packages
  - apt install -y docker.io
  - apt install -y docker-compose

  - echo "[CHECKPOINT]"
  - cd /opt
  - git clone https://github.com/chang432/youtube-cutter.git
  - mv youtube-cutter/docker ./
  - rm -rf youtube-cutter

  - reboot

  - chmod +x /opt/docker/start.sh
  - (crontab -l 2>/dev/null; echo "*/1 * * * * /opt/docker/start.sh >> /var/log/start.log 2>&1") | crontab -
  - chmod +x /opt/docker/cleanup.sh
  - (crontab -l; echo "*/10 * * * * /opt/docker/cleanup.sh >> /var/log/cleanup.log 2>&1") | crontab -
  - (crontab -l; echo "0 0 * * * echo "" > /var/log/cleanup.log") | crontab -
  