Resources:
  YoutubeCutterProdCheckPremLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
                - events.amazonaws.com
                - scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
      - PolicyName: LambdaExecutionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
                - s3:*
              Resource: arn:aws:s3:::*
            - Effect: Allow
              Action:
                - "lambda:InvokeFunction"
              Resource: "arn:aws:lambda:*:*:function:*"
            - Effect: Allow
              Action:
                - "ssm:GetParameter"
                - "SNS:Publish"
                - "dynamodb:*"
              Resource: "*"

  YoutubeCutterProdCheckPremEventbridgeRule:
    Type: AWS::Scheduler::Schedule
    Properties:
      ScheduleExpression: "rate(1 day)"
      FlexibleTimeWindow:
        Mode: 'OFF'
      ScheduleExpressionTimezone: Etc/UTC
      Target:
        Arn: !GetAtt YoutubeCutterProdCheckPremLambdaFunction.Arn
        RoleArn: !GetAtt YoutubeCutterProdCheckPremLambdaRole.Arn

  YoutubeCutterProdCheckPremLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/lambda/YoutubeCutterProdCheckPrem"
      RetentionInDays: 7

  # NOTE: If you want to update the layer, you need to change the s3 key because cfn won't detect an updated s3 file.
  YoutubeCutterProdCheckPremLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes: 
        - python3.9
      Content: 
        S3Bucket: "youtube-cutter-private-prod"
        S3Key: "check-prem-dep-layer.zip"
      Description: "Lambda layer containing python dependencies for youtube cutter premium expiration handling."
      LayerName: "YoutubeCutterProdCheckPremLambdaLayer"

  YoutubeCutterProdCheckPremLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Checks all premium subscriptions and remove the ones that are expired."
      FunctionName: "YoutubeCutterProdCheckPrem"
      Handler: check_prem_expiration.handle
      MemorySize: 128
      Role: !GetAtt YoutubeCutterProdCheckPremLambdaRole.Arn
      Runtime: python3.9
      Timeout: 300
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            return {
              'statusCode': 200
            }
      Layers:
        - !Ref YoutubeCutterProdCheckPremLambdaLayer
      LoggingConfig:
        LogGroup: !Ref YoutubeCutterProdCheckPremLambdaLogGroup